---
title: "R package `hyper.gam`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: 
  html:
    page-layout: full
    html-math-method: katex
    link-external-icon: true
    link-external-newwindow: true
number-sections: true
toc: true
toc-location: left
toc-depth: 4
toc-title: ''
editor: source
bibliography: hypergam.bib
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
vignette: >
  %\VignetteIndexEntry{applications}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---


The complete vignette of R [@R] package **`hyper.gam`** (v`r packageVersion('hyper.gam')`) 

> <https://tingtingzhan.quarto.pub/groupedhyperframe/bioinformatics_btaf430.html>

documents the derivation of single index predictors of scalar outcomes based on spatial and non-spatial single-cell imaging data.

The complete vignette exceeds the file size limit allowed on [CRAN](https://cran.r-project.org/package=hyper.gam).  



# Prerequisite

## Environment

Package **`hyper.gam`** (v`r packageVersion('hyper.gam')`) requires R version 4.5.0 (released 2025-04-11) or higher. Details are provided in the [book chapter](https://tingtingzhan.quarto.pub/groupedhyperframe/appendix/about.html#sec-envir).

## Installation

Packages **`hyper.gam`** (v`r packageVersion('hyper.gam')`) can be installed using the following command in R.

```{r}
#| eval: false
utils::install.packages('hyper.gam')
```


## Enhancement 

Package **`hyper.gam`** (v`r packageVersion('hyper.gam')`) `Enhances` package **`mgcv`** [@mgcv, v`r packageVersion('mgcv')`]. Details are provided in the [book chapter](https://tingtingzhan.quarto.pub/groupedhyperframe/appendix/about.html#hyper.gam).

## Dependency

The dependencies of package **`hyper.gam`** are detailed in the [book chapter](https://tingtingzhan.quarto.pub/groupedhyperframe/appendix/about.html#hyper.gam-1).


Package **`hyper.gam`** requires the *development versions* of the **`spatstat.*`** family of packages [@spatstat15; @spatstat05]. Installation instructions are provided in the [book chapter](https://tingtingzhan.quarto.pub/groupedhyperframe/appendix/dev.html).




# Acknowledgement

<!-- 

Most of this work was undertaken during Tingting Zhan’s leisure hours, with limited support from National Institutes of Health, U.S. Department of Health and Human Services grants

-   R01CA222847 ([I. Chervoneva](https://orcid.org/0000-0002-9104-4505), [T. Zhan](https://orcid.org/0000-0001-9971-4844), and [H. Rui](https://orcid.org/0000-0002-8778-261X))
-   R01CA253977 (H. Rui and I. Chervoneva).

--> 

The author thanks

-   [Erjia Cui](https://orcid.org/0000-0003-3576-2892)'s contribution to function `hyper_gam()`.



# References {.appendix}

::: {#refs}
:::
